### ISSUE TITLE
EPIC: Agile preparation 

### ISSUE THREAD

**Issue by noemichis** [noemichis/out-n-about#2]
**Acceptance criteria**
- All subtasks are checked. 

**Subtasks**
- [x] Create User Stories/EPICS and tasks.
- [x] Initialize Product Backlog.
- [x] Define Iterations.
- [x] Consult with mentor/tutor.
