### ISSUE TITLE
TASK : Wireframe

### ISSUE THREAD

**Issue by noemichis** [noemichis/out-n-about#29]
**Acceptance criteria**
- Good representation of HTML elements.

**Subtasks**
- [x] Wireframe for Desktop.
- [x] Wireframe for Mobile.
- [x] Landing page, Content page.
