### ISSUE TITLE
Tidy up code

### ISSUE THREAD

**Issue by noemichis** [noemichis/out-n-about#30]
**Acceptance criteria**

- [x] No commented out code
- [x] Description for all functions
- [x] No redundant code
- [x] No typos
- [x] No lines too long
- [x] Well organized
- [x] Simplify and refractor where possible

**Comment by noemichis** [comment]
Lines too long only in settings.py
