### ISSUE TITLE
EPIC: Set up project environment

### ISSUE THREAD

**Issue by noemichis** [noemichis/out-n-about#4]
**Acceptance Criteria**
- Early deployment to Heroku successful.  

**Subtasks**
- [x] Install Django and libraries
- [x] Create Project and App
- [x] Create ElephantSQL instance
- [x] Create env.py -> .gitignore
- [x] Update variables
- [x] Create Procfile
- [x] Early deploy to Heroku

**Comment by noemichis** [comment]
Early deployment successful: https://out-n-about.herokuapp.com/
